### ISSUE TITLE
img tag is not inside exported html

### ISSUE THREAD

**Issue by NicolasRoehm** [Niels-IO/next-image-export-optimizer#42]
Hi Niels,

Thank you for the great library, it's awesome! I wonder why my statically exported HTML doesn't contain any `img` tag.
It seems that javascript is required to display the image on the page, is this normal?

By default, NextJs is able to export the generated HTML :

![image](https://user-images.githubusercontent.com/6847846/192340675-6e8054d4-9d36-4b2f-988a-7b5630eedc59.png)

Best regards,

**Comment by Niels-IO** [comment]
Hi @NicolasRoehm,

Thanks for the bug report. I looked, and I know at least why this noscript img tag is not being generated.

This is how the export is taking place. I need to use the dynamic function with SSR off as there is a hydration error otherwise. When I would export the ExportedImage component directly, the noscript img tag would be generated but the hydration error occurs. 
```typescript

const DynamicExportedImage = dynamic(() => Promise.resolve(ExportedImage), {
  ssr: false,
});

export default function (props: ExportedImageProps) {
  const isStaticImage = typeof props.src === "object";
  const width = (isStaticImage && props.width) || (props.src as any).width;
  const height = (isStaticImage && props.height) || (props.src as any).height;

  return isStaticImage ? (
    <div style={isStaticImage ? { aspectRatio: width / height } : {}}>
      <DynamicExportedImage {...props} />
    </div>
  ) : (
    <DynamicExportedImage {...props} />
  );
}
```
I have to find a workaround for the hydration error. I think it happs because the environment variables are not accessible on the server side inside an imported module like the ExportedImage component.

**Comment by NicolasRoehm** [comment]
Hi @Niels-IO,
I've been playing with React & Next for only 2 weeks, so I'm not able to help much here.
Do you think something like this might help bypass the `ssr:false` https://github.com/vercel/next.js/discussions/35773#discussioncomment-3441844 ?

**Comment by NicolasRoehm** [comment]
Using something like https://github.com/martpie/next-transpile-modules ?
About environment variables, I see a lot of NextJs plugins uses their own `module.exports = {}` in a dedicated config file instead of the `next.config.js`. I don't know if it can help 😅

**Comment by Niels-IO** [comment]
Hi @NicolasRoehm,

The noscript tags should work properly now. Check out version 0.15.0 🙂
